source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'AlexMaxAdapter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'AppLovinSDK', '13.4.0'
  pod 'TPNiOS', '6.5.32' #(for TopOn , Also 6.4.94,6.5.31 is supported)
  #pod 'AnyThinkiOS', '6.5.32' #(for Taku , Also 6.4.94,6.5.31 is supported)

end
