# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'MaxCustomSDK' do

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Masonry'
  pod 'AppLovinSDK','13.4.0'
  pod 'AnyThinkiOS','6.4.93'
  # Pods for MaxCustomSDK
 
end

target 'MaxSDKAdapter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Masonry'
  pod 'AppLovinSDK','13.4.0'
  pod 'AnyThinkiOS','6.4.93'
end

  post_install do |installer|
    installer.generated_projects.each do |project|
      project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
           end
      end
    end
  end